#ifndef _DMA_DEF_H
#define _DMA_DEF_H

#define DMA_DIRECTION_PER_MEM			0x00
#define DMA_DIRECTION_MEM_PER			DMA_SxCR_DIR_0
#define DMA_DIRECTION_MEM_MEM			DMA_SxCR_DIR_1

#define DMA_CHANNEL_0							0x00
#define DMA_CHANNEL_1							DMA_SxCR_CHSEL_0
#define DMA_CHANNEL_2							DMA_SxCR_CHSEL_1
#define DMA_CHANNEL_3							(DMA_SxCR_CHSEL_1 | DMA_SxCR_CHSEL_0)
#define DMA_CHANNEL_4							DMA_SxCR_CHSEL_2
#define DMA_CHANNEL_5							(DMA_SxCR_CHSEL_2 | DMA_SxCR_CHSEL_0)
#define DMA_CHANNEL_6							(DMA_SxCR_CHSEL_2 | DMA_SxCR_CHSEL_1)
#define DMA_CHANNEL_7							(DMA_SxCR_CHSEL_2 | DMA_SxCR_CHSEL_1 | DMA_SxCR_CHSEL_0)

#define DMA_PRIORITY_LOW					0x00
#define DMA_PRIORITY_MEDIUM				DMA_SxCR_PL_0
#define DMA_PRIORITY_HIGH					DMA_SxCR_PL_1
#define DMA_PRIORITY_VERY_HIGH		(DMA_SxCR_PL_1 | DMA_SxCR_PL_0)

#define DMA_DATASIZE_BYTE					0x00
#define DMA_DATASIZE_HALFWORD			0x01
#define DMA_DATASIZE_WORD					0x02

#define DMA_FLOWCONTROL_DISABLE		0
#define DMA_FLOWCONTROL_ENABLE		1

#define DMA_INC_DISABLE						0
#define DMA_INC_ENABLE						1

#define DMA_CIRCULAR_DISABLE			0
#define DMA_CIRCULAR_ENABLE				1

#define DMA_BURST_SINGLE					0x00
#define DMA_BURST_INCR4						0x01
#define DMA_BURST_INCR8						0x02
#define DMA_BURST_INCR16					0x03

#endif
